export const data = [
  {
    src: "./assets/travel-img.PNG",
    title: "Travel Landing Page",
    text: "Built with Next.js, Tailwind CSS, and TypeScript, it offers a seamless and visually stunning experience, with a user-friendly interface designed to enhance your journey.",
    liveSite: "https://travvvel.vercel.app/",
    codeSite: "https://github.com/Azikenp/travel_app",
    tools: ["Next js", "typescript", "tailwind"],
  },
  {
    src: "./assets/crypto-verse-v2.PNG",
    title: "Crypto Verse-v2",
    text: "Discover trending coins and access comprehensive details about each coin, including market trends and price history.",
    liveSite: "https://crypt-verse-v2.vercel.app/",
    codeSite: "https://github.com/Azikenp/cryptVerse-v2.git",
    tools: ["React", "Redux-toolkit", "Antd", "Coinranking Api"],
  },
  {
    src: "./assets/hackerNews.png",
    title: "Hackernews",
    text: "This app fetches news feeds from the Hacker News API, debouncing to deliver 500 headlines at +30 per scroll, ensuring swift and responsive updates.",
    liveSite: "https://news-update-azikenp.vercel.app/",
    codeSite: "https://github.com/Azikenp/news-update.git",
    tools: ["React", "styled components"],
  },
  {
    src: "./assets/weather.png",
    title: "Mini weather app",
    text: "An advanced weather app, which uses OpenWeatherAPI and RaidAPI to deliver precise and up-to-date weather forecasts. With accurate predictions for temperature, you can stay informed with real-time updates and detailed weather conditions to fit your location.",
    liveSite: "https://weather-app-azikenp.vercel.app/",
    codeSite: "https://github.com/Azikenp/weather-app.git",
  },
  {
    src: "./assets/bookhub.png",
    title: "Book library",
    text: "A book search app, which utilizes the OpenLibrary API to help you find your next great read. Search for books by title and access detailed information about the searched book",
    liveSite: "https://book-library-azikenp.vercel.app/",
    codeSite: "https://github.com/Azikenp/book-library.git",
  },
];

export const techStack = [
  "Html",
  "Css",
  "javasript",
  "typeScript",
  "react",
  "next.js",
  "tailwind",
  "sass/scss",
  "bootstrap",
  "redux",
  "framer motion",
  "git",
  "github",
  "Material ui",
  "gsap",
  "Aceternity Ui",
  "shadCn",
];
