export const data = [
  {
    src: "./assets/travel-img.PNG",
    title: "Travel Landing Page",
    text: "Built with Next.js, Tailwind CSS, and TypeScript, it offers a seamless and visually stunning experience, with a user-friendly interface designed to enhance your journey.",
    liveSite: "https://travvvel.vercel.app/",
    codeSite: "https://github.com/Azikenp/travel_app",
    tools: ["Next js", "typescript", "tailwind"],
  },
  {
    src: "./assets/summarizer.PNG",
    title: "Summarizer",
    text: "This is an project which extracts news/article body from a URL and uses GPT to summarize the article content. Useful for text mining purposes. Leverages powerful and flexible web scraping engine (ScrapeNinja.net) with high-quality rotating proxies under the hood",
    liveSite: "https://summarizer-001.vercel.app/",
    codeSite: "https://github.com/Azikenp/AI-summarizer.git",
    tools: ["React", "Redux-toolkit", "tailwind"],
  },
  {
    src: "./assets/crypto-verse-v2.PNG",
    title: "Crypto Verse-v2",
    text: "Discover trending coins and access comprehensive details about each coin, including market trends and price history.",
    liveSite: "https://crypt-verse-v2.vercel.app/",
    codeSite: "https://github.com/Azikenp/cryptVerse-v2.git",
    tools: ["React", "Redux-toolkit", "Antd", "Coinranking Api"],
  },
  {
    src: "./assets/disney-plus.png",
    title: "Disney Plus",
    text: "A captivating Disney+ clone built with the TMDB API, showcasing a dynamic range of movie categories on an immersive and interactive landing page.",
    liveSite: "https://disney-plus-weld.vercel.app/",
    codeSite: "https://github.com/Azikenp/disney-plus.git",
    tools: ["React", "TMBD"],
  },
  {
    src: "./assets/hackerNews.png",
    title: "Hackernews",
    text: "This app fetches news feeds from the Hacker News API, debouncing to deliver 500 headlines at +30 per scroll, ensuring swift and responsive updates.",
    liveSite: "https://news-update-azikenp.vercel.app/",
    codeSite: "https://github.com/Azikenp/news-update.git",
    tools: ["React", "styled components"],
  },
];

export const techStack = [
  "Html",
  "Css",
  "javasript",
  "typeScript",
  "react",
  "next.js",
  "tailwind",
  "sass/scss",
  "bootstrap",
  "redux",
  "framer motion",
  "git",
  "github",
  "Material ui",
  "gsap",
  "Aceternity Ui",
  "shadCn",
];
